development:
    host: localhost
    username: fp365-dev-user
    password: 123123
    adapter: postgresql
    database: fp365-dev
    encode: unicode
    pool: 5
production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
