development:
    host: 127.0.0.1
    username: favre421421
    adapter: postgresql
    database: fp365_dev
    encode: unicode
production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
