# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: "75b34d0e0e38be67cc038e5b2325b6c92206966fa85d7238aae1096750a11b2534a028a2e80d8eb751b3fb4d085b29ea4c8ed92623c517f1e6ad877419d5f04f"
  stripe_public_key: "pk_test_XfVGPLwifVOqFqqVPo614nD4"
  stripe_secret_key: "sk_test_95aTVCg5aB1qOcU6gZNNdZlf"
  rocket_email: "admin"
  rocket_pw: "123x"
  url_link: "localhost:3000"
  gmail_username: "support@fantasy-phenom.com"
  gmail_password: "F@ntasyPhenom"
  gmail_domain: "gmail.com"
  aws_access_key_id: "AKIAJZZATDRLLD7PLCRQ"
  aws_secret_key_id: "UVQvT6zlqxC3HwR2TjZiDkuFT5GZMsVMZ5awVQRh"
  aws_region: "us-east-1"
  aws_bucket: "dev-fp365"
  deployment: "DEV"
  google_sheets_secret: '{"installed":{"client_id":"1033356681538-gc3dvqrmua3p64g8ql21k7uuo64drts4.apps.googleusercontent.com","project_id":"fp365-baseball","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"OCIdcQUny2jRSjkpq5r1gGEE","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: "75b34d0e0e38be67cc038e5b2325b6c92206966fa85d7238aae1096750a11b2534a028a2e80d8eb751b3fb4d085b29ea4c8ed92623c517f1e6ad877419d5f04f"
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  rocket_email: <%= ENV["ROCKET_EMAIL"] %>
  rocket_pw: <%= ENV["ROCKET_PW"] %>
  url_link: <%= ENV["URL"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  gmail_domain: <%= ENV["GMAIL_DOMAIN"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_key_id: <%= ENV["AWS_SECRET_KEY"] %>
  aws_region: "us-east-1"
  aws_bucket: "fp365"
  deployment: <%= ENV["DEPLOYMENT_CODE"] %>
  google_sheets_secret: <%= ENV["GOOGLE_SHEETS_SECRET"] %>