# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  rocket_email: <%= ENV["ROCKET_EMAIL"] %>
  rocket_pw: <%= ENV["ROCKET_PW"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rocket_email: <%= ENV["ROCKET_EMAIL"] %>
  rocket_pw: <%= ENV["ROCKET_PW"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>